export { BaseCatalogService } from "./BaseCatalogService"
export { macroregionCatalogService } from "./macroregionCatalogService"
export { ejeTematicoCatalogService } from "./ejeTematicoCatalogService"
export { institucionCatalogService } from "./institucionCatalogService"
export { territorioCatalogService } from "./territorioCatalogService"
export { estadoService } from "./estado-service"
export { tipoDocumentoService } from "./tipo-documento-service"
export { monedaService } from "./moneda-service"
export type * from "./types"
